apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-go
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
      - name: hello-go
        image: urunimi/hello-go:latest
        imagePullPolicy: Always
        ports:
        - name: hello-go-port
          containerPort: 5000
        readinessProbe:
          httpGet:
            path: /hello
            port: hello-go-port
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 400m
            memory: 200Mi
      restartPolicy: "Always"
