apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-go-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: hello-go
  minReplicas: 1
  maxReplicas: 16
  targetCPUUtilizationPercentage: 5